### ISSUE TITLE
WIM

### ISSUE THREAD

**Issue by gamer4eg** [laytya/SpamThrottle#10]
Можешь пожалуйста накатить мануал по настройке с вимом?
А то некоторые селеры шлют сообщения с доп символами, а при вставке они заменяются на обычные буквы или ? и этого селера не отфильтровать, + я так и не понял как идет фильтрация при рабочем виме.
(Ошибку вима при фильтрации уже скрыл добавлением слов ошибки в спамлист вима=)

**Comment by laytya** [comment]
Локаль какая? и скрины бы ошибки...

**Comment by gamer4eg** [comment]
Локаль ру.
Ошибка вама внутренняя, дескать вим пишет не могу прочесть сообщение-его ст полочил
Я тут про то что вим часть символов которые можно в чат писать не поддерживает.

**Comment by laytya** [comment]
скрин ошибки скинь
вим со спамтротлом не нада натраивать они и так работают вместе нормально
