### ISSUE TITLE
Option to disable 'Ban player chat' and 'Unban player chat' options in context menu.

### ISSUE THREAD

**Issue by caspervk** [laytya/SpamThrottle#12]
It would be great with an option to disable the 'Ban player chat' and 'Unban player chat' options in context menu when right-clicking other players.

**Comment by Monteo** [comment]
SpamThrottle.lua 

comment next lines

--= Unit popup options (right clicking on character name in chat)
--= This is really dirty. It would cause taint on later versions of WoW.
--============================
--[[	
UnitPopupButtons["SPAMTHROTTLE_ADD_PLAYERBAN"] = {
	text = "Ban player chat",
	dist = 0
}

UnitPopupButtons["SPAMTHROTTLE_REMOVE_PLAYERBAN"] = {
	text = "Unban player chat",
	dist = 0
}

table.insert(UnitPopupMenus["FRIEND"], 1, "SPAMTHROTTLE_ADD_PLAYERBAN");
table.insert(UnitPopupMenus["FRIEND"], 2, "SPAMTHROTTLE_REMOVE_PLAYERBAN");
--]]

**Comment by Monteo** [comment]
206 - 220 lines
