### ISSUE TITLE
hex code 

### ISSUE THREAD

**Issue by Monteo** [laytya/SpamThrottle#15]
![wowscrnshot_071718_223222](https://user-images.githubusercontent.com/24656088/42829015-617f46e2-8a13-11e8-9de3-b16bdb1a58c1.jpg)
![wowscrnshot_071718_224630](https://user-images.githubusercontent.com/24656088/42829016-61a4f9be-8a13-11e8-8a65-fc916c13c5d3.jpg)

**Comment by laytya** [comment]
fixed
