### ISSUE TITLE
error and ramdomly working

### ISSUE THREAD

**Issue by waytoomuchgaming** [laytya/SpamThrottle#4]
Hi

Latest version, basic setup.
1) I got this : http://i.imgur.com/SRE7VaQ.png
2) SpamThrottle seem to randomly block messages. 50% of the spam is still here, 50% of filtered messages are legit (i see that if i check the color messages instead of blocking them - eg : http://i.imgur.com/LAoTQGI.png)

**Comment by laytya** [comment]
please provide more info - more screens of miss messages, and your block words in settings
